linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - errcheck
    - errorlint
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gocritic
    - gofmt
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - exportloopref
    - staticcheck
    - stylecheck
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - whitespace
    - revive

# output configuration options
output:
# colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
  gocritic:
    disabled-checks:
      - ifElseChain
  golint:
    min-confidence: 0
  maligned:
    suggest-new: true
  dogsled:
    max-blank-identifiers: 3
# workaround for ct-logic-uni-rev only. Too avoid too many fixes at the first place.
  revive:
    rules:
      - name: var-naming
        arguments: [["ID"], []]
  stylecheck:
    checks: ["all", "-ST1003"]

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - goconst
        - gosec
        - scopelint
        - ineffassign
    - path: \.go
      linters:
        - goconst
        - nakedret
        - typecheck
        - gofmt
    - path: utils/constants/.go
      linters:
        - revive
    - path: internal/entity/.go
      linters:
        - revive

run:
  timeout: 5m
